### ISSUE TITLE
Runtime exceptions with Apache HTTP backend

### ISSUE THREAD

**Issue by asoltysik** [pepegar/hammock#114]
Not sure what your policy on runtime exception is, so I just leave this issue for your consideration - whether you want to make it typesafe or not.

## First error - `ClientProtocolException`

Reproduction:

``` scala
import cats.effect.IO
import hammock._
import hammock.jvm.Interpreter

implicit val interpreter = Interpreter[IO]

Hammock.
  .request(Method.GET, uri"github.com", Map())
  .exec[IO]
  .unsafeRunSync
```

Result:
```
org.apache.http.client.ClientProtocolException: org.apache.http.ProtocolException: Target host is not specified
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
  at hammock.jvm.Interpreter.$anonfun$doReq$3(Interpreter.scala:41)
  at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:167)
  at cats.effect.IO.unsafeRunTimed(IO.scala:307)
  at cats.effect.IO.unsafeRunSync(IO.scala:242)
  ... 36 elided
Caused by: org.apache.http.ProtocolException: Target host is not specified
  at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
  at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
  ... 43 more
```

## Second error - `UnknownHostException`

Easiest way to reproduce this is to unplug your Internet cable / turn off wifi and run:

``` scala
import cats.effect.IO
import hammock._
import hammock.jvm.Interpreter

implicit val interpreter = Interpreter[IO]

Hammock.
  .request(Method.GET, uri"http://github.com", Map())
  .exec[IO]
  .unsafeRunSync
```

Result:

```
java.net.UnknownHostException: github.com: Temporary failure in name resolution
  at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
  at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
  at java.net.InetAddress.getAllByName(InetAddress.java:1192)
  at java.net.InetAddress.getAllByName(InetAddress.java:1126)
  at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
  at hammock.jvm.Interpreter.$anonfun$doReq$3(Interpreter.scala:41)
  at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:167)
  at cats.effect.IO.unsafeRunTimed(IO.scala:307)
  at cats.effect.IO.unsafeRunSync(IO.scala:242)
  ... 36 elided
```

**Comment by pepegar** [comment]
Hi @asoltysik , thanks for reporting.

I don't know if there's a way to solve this. It's true that's causing exceptions, but that's because youre _executing_ the `IO[HttpResponse]` action with the `unsafeRunSync` function. The first three lines are pure:

```scala
Hammock.
  .request(Method.GET, uri"github.com", Map())
  .exec[IO]
```

But when you want to execute the `IO` action, with `unsafeRunSync` (`IO[A] => A`), exceptions will be thrown if they're thrown from the inner java code.

You can control exceptions ocurring when executing an IO action by using the `runAsync` method instead of `unsafeRunSync`. For example:

```scala
Hammock.
  .request(Method.GET, uri"github.com", Map())
  .exec[IO]
  .runAsync {
    case Left(x) => IO(println(x.getMessage))
    case Right(x) => IO(println(x))
  }
```

**Comment by pepegar** [comment]
It's right too that we should probably exemplify that kind of behaviour in our docs.

**Comment by asoltysik** [comment]
This actually explained a lot for me, thanks!
